### ISSUE TITLE
Right padding not correct

### ISSUE THREAD

**Issue by benwainwright** [dbordak/telephone-line#100]
Hi there

I've just installed telephone line and seems that with my configuration there isn't enough padding to line the right hand side up with the edge of the frame?

<img width="344" alt="Screenshot 2019-04-10 at 22 31 34" src="https://user-images.githubusercontent.com/3321885/55914992-724d9600-5be0-11e9-96b8-40c05eec66ef.png">

**Comment by dbordak** [comment]
Hi, this can happen for a number of reasons, but I'd need to see your config to figure it out. If you're using the default config, then it's probably something to do with your font.
