### ISSUE TITLE
Column number indicator one-based

### ISSUE THREAD

**Issue by Riyyi** [dbordak/telephone-line#101]
Since Emacs 26 there is the option:
`(setq column-number-indicator-zero-based nil)`
to display the column number as one-based instead of zero-based.
But its not read by telephone-line yet, is there some work-around for this?

**Comment by dbordak** [comment]
Hey, forgot to mention here but I patched this last week. Does it work for you now?

**Comment by Riyyi** [comment]
Did you forget to push it? Github and melpa show the last commit is from January, or am I missing something?

**Comment by dbordak** [comment]
Oh, oops.

**Comment by Riyyi** [comment]
Yes, this fixed the issue, thanks!
