### ISSUE TITLE
Separator not rendering correctly when window is inactive.

### ISSUE THREAD

**Issue by stockersky** [dbordak/telephone-line#106]
I spent some time designing my telephone-line modeline and was happy about it :

![active_ok](https://user-images.githubusercontent.com/22478549/68085738-770bbd00-fe44-11e9-9c92-e79de0e287b6.png)

Then I realized that the modeline was empty on the inactive windows...
First, I just set it up to use the same face whatever active or inactive:

```
(use-package telephone-line
  :ensure t
  :config
  (setq telephone-line-faces
      '((face0 . (my-modeline-face0 . my-modeline-face0))
        (face1 . (my-modeline-face1 . my-modeline-face1))
        (face2 . (my-modeline-face2 . my-modeline-face2))
        (face3 . (my-modeline-face3 . my-modeline-face3))
        (nil . (mode-line . mode-line-inactive))))

```

But the active and inactive modelines would render as this
![active_KO](https://user-images.githubusercontent.com/22478549/68085742-7d9a3480-fe44-11e9-9107-4e4ac13de1a0.png)

Here is an example of how I define a face: 
```
(defface my-modeline-face3
  '((t :foreground "gold"
       :background "chocolate4"
       :weight bold
       ;; :inherit mode-line
       ))
   :group 'telephone-line )
```

I tried with ```inherit mode-line```. It changed nothing.

Then I tried a dedicated face for the inactive windows:

```
(defface my-modeline-face3-inactive
  '((t :foreground "gold"
       :background "blue"
       :inherit mode-line-inactive
       ))
  "Face for global variables."
   :group 'telephone-line )

(use-package telephone-line
  :ensure t
  :config
  (setq telephone-line-faces
      '((face0 . (my-modeline-face0 . my-modeline-face3-inactive))
	(face1 . (my-modeline-face1 . my-modeline-face3-inactive))
	(face2 . (my-modeline-face2 . my-modeline-face3-inactive))
	(face3 . (my-modeline-face3 . my-modeline-face3-inactive))
	(nil . (mode-line . mode-line-inactive))))

```

As a result, active modeline is correctly rendered, but the inactive one still has messy separator. (cubed separator has the same problem).

![modeline_ko2](https://user-images.githubusercontent.com/22478549/68085821-42e4cc00-fe45-11e9-94b0-428e66a40e26.png)

**Comment by stockersky** [comment]
Alright, I found out!

As I use a quite big font size for coding (13), the default telephone-line modeline size was too small.

Increasing the telephone-line modeline height solved the problem.
```
(setq telephone-line-height 22)
```

**Comment by dbordak** [comment]
This is actually an issue with when your font is defined -- the default height of `telephone-line` is the height of the font you've selected, but if you change the size of your font _after_ `telephone-line` is loaded, it can lead to this issue.

There is a pending PR which will fix this fully, once that's merged I'd probably recommend you drop setting the height manually -- otherwise, you'd need to change it whenever you change your font :P
