### ISSUE TITLE
I'm too dumb: passing arguments to segments?

### ISSUE THREAD

**Issue by c-alpha** [dbordak/telephone-line#131]
I have this in my config:
```elisp
(setq telephone-line-rhs '((nil    . (telephone-line-misc-info-segment))
                           (accent . ((telephone-line-atom-eol-segment t) (telephone-line-atom-encoding-segment t)))
                           (evil   . (telephone-line-airline-position-segment))))
```

Apparently I'm trying to pass arguments to the two segments in the middle part. But to no avail; it still shows "LF UTF-8" despite passing `t` to the two hide arguments.

I searched the Interwebs, but couldn't find an example of how it's done. Any hints appreciated.

**Comment by dbordak** [comment]
That _should_ work. Is it maybe just that the config isn't applied on the current buffer yet? I can't really think of anything else.

**Comment by c-alpha** [comment]
Thanks for responding!

> That _should_ work. Is it maybe just that the config isn't applied on the current buffer yet? I can't really think of anything else.

Hm, I put the above elsip snippet in the scratch buffer, then `eval-region` on it, and open a file in a new frame. `LF` and `UTF-8` indicators are shown. Perhaps a `funcall` is needed somewhere?
