### ISSUE TITLE
Problems with theme-changer

### ISSUE THREAD

**Issue by shackra** [dbordak/telephone-line#18]
I use [theme-changer](https://github.com/hadronzoo/theme-changer) to make Emacs switch the theme depending of the hour of the day, when the theme is changed from a light theme to a darker theme, some colors remains in the separators of telephone-line (as can be seen in the screenshot)

![captura_27-10-2015-171119](https://cloud.githubusercontent.com/assets/1055216/10775664/07db749c-7cd0-11e5-9234-5208e5c88a8e.png)

**Comment by dbordak** [comment]
This is a case of a missing feature rather than a bug -- I never handled theme switching.

Before I get started on this, are you using the default mode theme-changer (deftheme) or color-theme?

**Comment by dbordak** [comment]
As a temporary solution, you should be able to run the following to reset the separators:

```
(unload-feature 'telephone-line-separators 1)
(require 'telephone-line-separators)
```

**Comment by shackra** [comment]
The default 

El 27 de octubre de 2015 23:05:56 CST, Daniel Bordak <notifications@github.com> escribió:
>This is a case of a missing feature rather than a bug -- I never
>handled theme switching.
>
>Before I get started on this, are you using the default mode
>theme-changer (deftheme) or color-theme?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/dbordak/telephone-line/issues/18#issuecomment-151726434

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dbordak** [comment]
After looking into a bit, I see that this is a bit harder than I'd like due to the way memoize works. I was planning on getting rid of it anyway, so I should be able to fix this along with #17. I'll work on this over the weekend, I think.

**Comment by dbordak** [comment]
Alright, this should be fixed with the latest update.

**Comment by shackra** [comment]
Yup, it works!

Thank you very much!
