### ISSUE TITLE
Box around text: make the mode-line look good (if possible)

### ISSUE THREAD

**Issue by shackra** [dbordak/telephone-line#21]
My mode-line looks skinny, lol. I tried changing the face and adding a `box around text`, however, it doesn't look good with this mode-line turned on.

![screenshot](https://cloud.githubusercontent.com/assets/1055216/18493890/2ab80bb2-79d0-11e6-8a15-640e78b285f9.png)

Maybe a workaround for this is not trying anything far-fetched and just modify the theme of my telephone-line to use the same colors and to banish the separators (I don't know exactly how to do that, hope the documentation is enough for me)

**Comment by dbordak** [comment]
You can directly change the thickness by setting `telephone-line-height`. Otherwise it fits to the text height.

If you want to remove the separators, you can set them to `telephone-line-nil` (e.g. `(setq telephone-line-primary-left-separator 'telephone-line-nil)`.

**Comment by shackra** [comment]
Cool! I had to set it up to 30 thought.

![2](https://cloud.githubusercontent.com/assets/1055216/18507599/4251237c-7a2e-11e6-8030-f5c3057277d3.png)

any idea how to diminish the light above and the shadow under the mode-line?

**Comment by dbordak** [comment]
That's just the box settings on your mode-line, part of your color theme. You can change that by customizing the mode-line face, IIRC.

**Comment by shackra** [comment]
This is how is done:

```
(custom-set-faces
   '(mode-line ((t (:box nil))))
   '(mode-line-inactive ((t (:box nil))))
   '(mode-line-highlight ((t (:box nil)))))
```

Thanks for the support, @dbordak !
