### ISSUE TITLE
Two custom fragments are flickering/banishing under certain circumstances

### ISSUE THREAD

**Issue by shackra** [dbordak/telephone-line#22]
So, I have these two custom fragments that show the branch and the flycheck status on the mode-line (duh!) and they flicker/banish under certain circumstances.

![issue](https://cloud.githubusercontent.com/assets/1055216/18578414/08337cb4-7bad-11e6-8470-5534559daf19.gif)

As you can see, the fragments takes few seconds to appear after a file from a project is visited, also, both banish if flycheck reports an issue and when editing they both flicker; this issue had not happened at org-mode or any other major-mode that have no flycheck checker available/enabled. I'm not sure how to debug this issue, there is the relevant source code:

```
(telephone-line-defsegment* shackra-vc-info
      (when vc-mode
        (cond ((string-match "Git[:-]" vc-mode)
               (let ((branch (mapconcat 'concat (cdr (split-string vc-mode "[:-]")) "-")))
                 (concat
                  (propertize (format " %s" (all-the-icons-alltheicon "git")) 'face `(:foreground "orange" :height 1.3) 'display '(raise -0.1))
                  " · "
                  (propertize (format "%s" (all-the-icons-octicon "git-branch"))
                              'face `(:foreground "yellow" :height 1.3 :family ,(all-the-icons-octicon-family))
                              'display '(raise -0.1))
                  (propertize (format " %s" branch) 'face `(:foreground "yellow" :height 0.9)))))
              ((string-match "SVN-" vc-mode)
               (let ((revision (cadr (split-string vc-mode "-"))))
                 (concat
                  (propertize (format " %s" (all-the-icons-faicon "cloud")) 'face `(:height 1.3) 'display '(raise -0.1))
                  (propertize (format " · %s" revision) 'face `(:height 0.9)))))
              (t (format "%s" vc-mode)))))
    (telephone-line-defsegment* shackra-flycheck-status
      (let* ((text (pcase flycheck-last-status-change
                     (`finished (if flycheck-current-errors
                                    (let ((count (let-alist (flycheck-count-errors flycheck-current-errors)
                                                   (+ (or .warning 0) (or .error 0)))))
                                      (propertize (format " ✖ %s problema%s" count (unless (eq 1 count) "s"))) 'face `(:foreground "orange"))
                                  (propertize " ✔ Sin problemas" 'face `(:foreground "dark grey"))))
                     (`running     (propertize " ⟲ En ejecución") 'face `(:foreground "deep sky blue"))
                     (`no-checker  (propertize " ⚠ No existe revisor" 'face `(:foreground "dim grey")))
                     (`not-checked (propertize " ✖ Sin revisar" 'face `(:foreground "dim grey")))
                     (`errored     (propertize " ⚠ Error" 'face `(:foreground "tomato")))
                     (`interrupted (propertize " ⛔ Interrumpido" 'face `(:foreground "tomato")))
                     (`suspicious  ""))))
        (propertize text
                    'help-echo "Muestra errores detectados por Flycheck"
                    'local-map (make-mode-line-mouse-map
                                'mouse-1 (lambda () (interactive) (flycheck-list-errors))))))

    (setf telephone-line-lhs
          '((accent . (shackra-line-buffer-segment shackra-buffer-vc-modified-segment))
            (nil .  (shackra-vc-info shackra-flycheck-status))))
```

**Comment by dbordak** [comment]
Well, I figured out the banishing. A few of your cases are formatted incorrectly -- on your flycheck segment, the calls to propertize in running and finished don't have the face inside them -- they're `(propertize "stuff") 'face (...)` instead of `(propertize "stuff" 'face (...))`

Here's the corrected version:
```
(telephone-line-defsegment* shackra-flycheck-status
    (let* ((text (pcase flycheck-last-status-change
                   (`finished (if flycheck-current-errors
                                  (let ((count (let-alist (flycheck-count-errors flycheck-current-errors)
                                                 (+ (or .warning 0) (or .error 0)))))
                                    (propertize (format " ✖ %s problema%s" count (unless (eq 1 count) "s")) 'face `(:foreground "orange")))
                                (propertize " ✔ Sin problemas" 'face `(:foreground "dark grey"))))
                   (`running     (propertize " ⟲ En ejecución" 'face `(:foreground "deep sky blue")))
                   (`no-checker  (propertize " ⚠ No existe revisor" 'face `(:foreground "dim grey")))
                   (`not-checked (propertize " ✖ Sin revisar" 'face `(:foreground "dim grey")))
                   (`errored     (propertize " ⚠ Error" 'face `(:foreground "tomato")))
                   (`interrupted (propertize " ⛔ Interrumpido" 'face `(:foreground "tomato")))
                   (`suspicious  ""))))
      (propertize text
                  'help-echo "Muestra errores detectados por Flycheck"
                  'local-map (make-mode-line-mouse-map
                              'mouse-1 (lambda () (interactive) (flycheck-list-errors))))))
```

By the way, I quite like these, and I was intending on adding a flycheck segment anyway, would you mind if I copied this?

**Comment by shackra** [comment]
Wow, you are awesome and I'm very distracted lol.

I absolutely don't mind, however, you better ask the real author of that piece of beauty https://github.com/domtronn/all-the-icons.el ;) 

Thank you very much! 

El 16 de septiembre de 2016 17:51:50 GMT-06:00, Daniel Bordak <notifications@github.com> escribió:
>Well, I figured out the banishing. A few of your cases are formatted
>incorrectly -- on your flycheck segment, the calls to propertize in
>running and finished don't have the face inside them -- they're
>`(propertize "stuff") 'face (...)` instead of `(propertize "stuff"
>'face (...))`
>
>Here's the corrected version:
>```
>(telephone-line-defsegment* shackra-flycheck-status
>    (let* ((text (pcase flycheck-last-status-change
>                   (`finished (if flycheck-current-errors
>(let ((count (let-alist (flycheck-count-errors flycheck-current-errors)
>                                   (+ (or .warning 0) (or .error 0)))))
>(propertize (format " ✖ %s problema%s" count (unless (eq 1 count) "s"))
>'face `(:foreground "orange")))
>     (propertize " ✔ Sin problemas" 'face `(:foreground "dark grey"))))
>(`running     (propertize " ⟲ En ejecución" 'face `(:foreground "deep
>sky blue")))
>(`no-checker  (propertize " ⚠ No existe revisor" 'face `(:foreground
>"dim grey")))
>(`not-checked (propertize " ✖ Sin revisar" 'face `(:foreground "dim
>grey")))
>   (`errored     (propertize " ⚠ Error" 'face `(:foreground "tomato")))
>(`interrupted (propertize " ⛔ Interrumpido" 'face `(:foreground
>"tomato")))
>                   (`suspicious  ""))))
>      (propertize text
>                  'help-echo "Muestra errores detectados por Flycheck"
>                  'local-map (make-mode-line-mouse-map
>          'mouse-1 (lambda () (interactive) (flycheck-list-errors))))))
>```
>
>By the way, I quite like these, and I was intending on adding a
>flycheck segment anyway, would you mind if I copied this?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dbordak/telephone-line/issues/22#issuecomment-247733866

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dbordak** [comment]
Hey, don't know if you're still using this setup, but wanted to warn you that the latest commit I just pushed broke backwards compat on defsegment. You now need an empty arglist after the name (as though it were defun, etc).

**Comment by shackra** [comment]
I still use this xD

Thanks for the warning, I will modify my code accordingly
