### ISSUE TITLE
Pad cursor position to prevent resizing

### ISSUE THREAD

**Issue by Johnson-A** [dbordak/telephone-line#26]
When the cursor position changes, the size of the coordinates `(x, y` can change and cause the section they are in to resize. It would be nice if, given there is enough mode-line space, to pad this information so that all other sections aren't shifted over. There is already an option to increase the extra padding for separators, maybe the space from this extra padding could be used so that all separators remain in the same position.

**Comment by dbordak** [comment]
It already is padded -- 3 characters for line, 2 for column. I figured those would be reasonable, but I guess you hit the area that doesn't cover. I could make it configurable, sure.

**Comment by Johnson-A** [comment]
Great, maybe it would be useful to have a screenshot for the right side as well, showing the padded position.
