### ISSUE TITLE
Allow for more sections other than (evil, accent, nil)

### ISSUE THREAD

**Issue by Johnson-A** [dbordak/telephone-line#27]
It might be useful to allow for more section types to be added, even if they only differ in color. In addition, these might need to be non-symmetric, ie only only the left or right side.

**Comment by dbordak** [comment]
This is what I meant by #13. As for asymmetrical segments, that should already work, does it not? There might be some weirdness when it comes to center segments being non-nil, but I'd have to check.

**Comment by Johnson-A** [comment]
My bad, missed that issue!

**Comment by dbordak** [comment]
Don't know if you still use this, but I just fixed this issue in my latest commit.
