### ISSUE TITLE
xah fly keys integration

### ISSUE THREAD

**Issue by thorstengrothe** [dbordak/telephone-line#28]
Is it possible to use it with xah-fly-keys?

[http://ergoemacs.org/misc/ergoemacs_vi_mode.html](url)

Xah-fly-keys basically uses two modes

```
xah-fly-command-mode-activate
xah-fly-insert-mode-activate
```
very simple. I would be nice if 

`telephone-line-evil-tag-segment` could work with it.

Thorsten

**Comment by dbordak** [comment]
Link appears to be dead?

But yeah, this sounds like it'd be easy to add support for.

**Comment by dbordak** [comment]
Alright, just added support for it. It's a separate `telephone-line-xah-fly-keys-segment` -- I agree it'd be better to have one segment that can do either, but it'd be a bit difficult to implement as such since they're defined on package load (as in, on loading `evil` or `xah-fly-keys`).

**Comment by thorstengrothe** [comment]
Sorry for the dead link, this one is right
[xah fly keys](https://github.com/xahlee/xah-fly-keys)

Oh that are great news, wil try it soon.
Thanks for the super fast support!!

**Comment by dbordak** [comment]
Oh, right, for the face symbol, use evil -- that one *is* overloaded to handle both.

Example:

```
  (setq telephone-line-lhs
        '((evil . (telephone-line-xah-fly-keys-segment))
        ...))
```

**Comment by thorstengrothe** [comment]
Great, looks really good!

**Comment by dbordak** [comment]
Oh, right, I also added support for ~telephone-line-evil-use-short-tag~ on this as well, but since there's only two modes, it's even abbreviated to a single character.
