### ISSUE TITLE
Rendering Error

### ISSUE THREAD

**Issue by gigavinyl** [dbordak/telephone-line#37]
I'm trying to use the default evil config for telephone-line and I'm receiving this error
```
Error during redisplay: (eval (telephone-line-separator-render telephone-line-abs-right (telephone-line-face-map (quote evil)) (telephone-line-face-map (quote accent)))) signaled (void-function alist-get)
Error during redisplay: (eval (telephone-line-add-subseparators (quote (telephone-line-airline-position-segment)) telephone-line-abs-hollow-right (quote evil))) signaled (void-function alist-get)
```
The relevant part of my `init.el` is
``` emacs-lisp
(use-package telephone-line
  :ensure t
  :config
  (telephone-line-evil-config))
```

**Comment by dbordak** [comment]
Oops, looks like alist-get was added in Emacs 25. I'll switch it to something else.

**Comment by dbordak** [comment]
Alright, should be fixed once the next build is up.

**Comment by dbordak** [comment]
Does it work for you now?

**Comment by gigavinyl** [comment]
@dbordak Yes it works perfectly. Thanks :smile:

**Comment by shackra** [comment]
I'm experiencing this bug:

```
Error during redisplay: (eval (telephone-line-add-subseparators (quote (telephone-line-misc-info-segment telephone-line-major-mode-segment)) telephone-line-abs-hollow-right (quote nil))) signaled (wrong-number-of-arguments (0 . 0) 1)
```

**Comment by dbordak** [comment]
The code you quoted doesn't appear to have anything wrong with it. The issue must have come from somewhere else. Can I see more of your config, or is your .emacs.d repo up to date?

**Comment by shackra** [comment]
Sure, take a look! https://github.com/shackra/.emacs.d/blob/master/configuracion.org#telephone-line

**Comment by dbordak** [comment]
You need to update your defsegment forms

From this:

```emacs-lisp
(telephone-line-defsegment
  body)
```

To this:

```emacs-lisp
(telephone-line-defsegment ()
  body)
```

Sorry, my fault, tried to make this change more obvious but I don't think I got it across very well.

**Comment by shackra** [comment]
Thanks!
