### ISSUE TITLE
Add a segment option to display only when mode-line is active/inactive

### ISSUE THREAD

**Issue by 0rdy** [dbordak/telephone-line#38]
As far as I know, there's `telephone-line-selected-window-active` for a custom segment, but it's kinda hard to use this function with the built-in telephone-line segments.
I mean add something like:
```emacs-lisp
  (setq telephone-line-rhs
        '((nil . (telephone-line-vc-segment :active))
```

**Comment by dbordak** [comment]
Oh, that's a pretty good idea. I'll work on this soon.

**Comment by dbordak** [comment]
Ok, I've added it. Difference from how you demonstrated, modifiers need to be inside another nested list; your example would become 

```emacs-lisp
  (setq telephone-line-rhs
        '((nil . ((telephone-line-vc-segment :active)))
```

If you had more subsegments, this would look like

```emacs-lisp
  (setq telephone-line-rhs
        '((nil . (hi-im-a-segment
                  (telephone-line-vc-segment :active)
                  im-another-segment))
```

**Comment by dbordak** [comment]
I just added an `:inactive` modifier, though I can't think of any reason anyone would want to use that.

**Comment by 0rdy** [comment]
I confirm an `:inactive` modifier isn't so useful as an `:active` modifier, but maybe someone would want to display the major-mode segment instead of the minor-mode segment in inactive mode-line or whatever. I think it will be better to cover all cases at once. In any way, it makes telephone-line more flexible.

Now I got the latest telephone-line update from Melpa. Yes, works perfectly. Thanks you for this change and nice package.

**Comment by dbordak** [comment]
Oh, sorry, I didn't realize you'd asked for `:inactive`, I was just saying that because I implemented it for completion's sake rather than any use case I could forsee.

**Comment by dbordak** [comment]
I've opened #40 to consider extending this functionality. If you have any more ideas, please suggest them there.

Also, thanks for suggesting this in the first place! I don't think I would have thought of it otherwise.
