### ISSUE TITLE
ryo modal mode

### ISSUE THREAD

**Issue by thorstengrothe** [dbordak/telephone-line#39]
I switched from xah-fly-keys to ryo modal mode. I like telephone line very much, would it be much work to make it compatible with [ryo modal mode?](https://github.com/Kungsgeten/ryo-modal)

Regards
Thorsten

**Comment by dbordak** [comment]
I've just added support for this with the latest commit, however there are two considerations due to the way this package works (that is, only being enabled while in "normal" mode, whereas the other packages are always enabled). First, you need to make sure the package is actually loaded (otherwise the segment will show up blank until you've enabled the mode, not a big deal I guess). Second, it has its own colorsym, `ryo`. Here's an example:

```emacs-lisp
  (setq telephone-line-lhs
        '((ryo    . (telephone-line-ryo-modal-segment))
          (...)))
```

**Comment by thorstengrothe** [comment]
Thank you, I will test and report...

**Comment by thorstengrothe** [comment]
It works fine :-) The only thing is, that the right side is gray and not red like in your screenshots,
I use [Spacemacs theme](https://github.com/nashamri/spacemacs-theme) and [Doom Theme](https://github.com/hlissner/emacs-doom-theme). This is my config with use-package:

```
(use-package telephone-line
  :ensure t
  :config
  (use-package telephone-line-separators)
  (setq telephone-line-lhs
        '((ryo    . (telephone-line-ryo-modal-segment))
          (accent . (telephone-line-vc-segment
                     telephone-line-erc-modified-channels-segment
                     telephone-line-process-segment))
          (nil    . (telephone-line-minor-mode-segment
                     telephone-line-buffer-segment))))
  (setq telephone-line-rhs
        '((nil    . (telephone-line-misc-info-segment))
          (accent . (telephone-line-major-mode-segment))
          (evil   . (telephone-line-airline-position-segment))))

  ;; ABS
  (setq telephone-line-primary-right-separator 'telephone-line-abs-left
        telephone-line-secondary-right-separator 'telephone-line-abs-hollow-left)
  (setq telephone-line-height 24
        telephone-line-evil-use-short-tag t)
  (telephone-line-mode 1)
  )
```

With Spacemacs theme it looks like this (see the right side):
![bildschirmfoto_2017-05-29_21-07-23](https://cloud.githubusercontent.com/assets/19598706/26560064/e450d712-44b3-11e7-93e3-e41a56644022.png)

Doom theme seems to break the separators and the right side is not red too, see here:
![bildschirmfoto_2017-05-29_21-17-31](https://cloud.githubusercontent.com/assets/19598706/26560122/4b3c4466-44b4-11e7-862b-3181c6270cc6.png)

No big deal, thanks for the fast support!
Thorsten

**Comment by 0rdy** [comment]
@thorstengrothe you have the different color "mode", i.e. your right side uses evil color instead of ryo. You could use the following:
```emacs-lisp
(ryo   . (telephone-line-airline-position-segment)
```
Or set both segment to evil if you want the same color.
