### ISSUE TITLE
telephone-line-flat causes error in terminal emacs

### ISSUE THREAD

**Issue by bklaase** [dbordak/telephone-line#45]
Hi!
I use emacs for notetaking on android, using termux and your statusline is great on small displays!
However, I would like the option of disabling seperators to save even more space. 

the `telephone-line-flat` separator does exactly this in gui mode:
![image](https://user-images.githubusercontent.com/8513117/28995133-fa966962-79e0-11e7-92a2-ba52cc4ba679.png)

However for the terminal, this happens:
![image](https://user-images.githubusercontent.com/8513117/28995136-13c3dee2-79e1-11e7-93b4-6d5b7a4d30f3.png)

**Comment by bklaase** [comment]
It would be nice if the seperator could be something else as just a "space", because then no room is actually being saved :). Not render at all is the dream!

Maybe as an afterthought. I would be great to have the ability to have utf-8 glyphs used, EVEN when drawing *is* available. Like "forcing" using the alt-char. There are many great symbols ([example](https://www.w3schools.com/charsets/ref_utf_block.asp)) to use as separators (I'll make a separate issue for this, if you prefer)

**Comment by dbordak** [comment]
Did you try `telephone-line-nil`? That one overrides the render method to render nothing, IIRC it should work fine in terminal. (There's a reason for it being separate from `flat`, but I can't remember it right now)

**Comment by dbordak** [comment]
Oh right, I remember why it's separate from flat. Flat has a height, nil obviously can't; the only way to make the mode-line larger than your font demands is by inserting an image of the desired height.

**Comment by bklaase** [comment]
I see!
No I didn't use the `nil` variant, I will try forthwith!

.... AAAAAAND I've wasted your time.. :)
Shall I make a separate issue about the utf-8 glyph ALWAYS one, or is that another thing that is already possible? ;)
