### ISSUE TITLE
Allow utf-8 glyphs regardless of gui/terminal mode

### ISSUE THREAD

**Issue by bklaase** [dbordak/telephone-line#46]
As mentioned in this issue: #45,  It would be great to have the ability to have utf-8 glyphs used, EVEN when drawing *is* available. Like "forcing" using the alt-char. There are many great symbols ([example](https://www.w3schools.com/charsets/ref_utf_block.asp)) to use as separators. 

Would this be possible?

**Comment by bklaase** [comment]
Not that I'm in a hurry, but I would love to give something back to this project. Could you point me in the general direction for where decision is made to render separator as a glyph, or .xpm? I'll try to achieve the effect and make a PR.

**Comment by bklaase** [comment]
in `telephone-line-utils.el`

```lisp
(cl-defmethod telephone-line-separator-render ((obj telephone-line-separator) foreground background)
  (let ((fg-color (telephone-line-separator--arg-handler foreground))
        (bg-color (telephone-line-separator--arg-handler background)))
    (if window-system
        (telephone-line-separator-render-image obj fg-color bg-color)
(telephone-line-separator-render-unicode obj fg-color bg-color))))
```
it should suffice to create some *custom* variable like "telephoneline-seperator-always-unicode" and add that to the `if` clause. I'll make a PR.

**Comment by dbordak** [comment]
No, I want to make a new subclass rather than an option. Sorry, I've been kinda busy recently

**Comment by dbordak** [comment]
Ok, just pushed a fix for this, I think. The advantage of doing it this way, though I'm not sure anyone will ever use this, is that you can use unicode and XPM separators together.

**Comment by dbordak** [comment]
Just pushed another commit to name them better.

By the way, thank you for offering to make a PR!

**Comment by bklaase** [comment]
ah, I see now what you meant. Very nice solution! I will start experimenting with it immediately :)

**Comment by bklaase** [comment]
woops:

![image](https://user-images.githubusercontent.com/8513117/29921228-28882b6a-8e51-11e7-9f2c-eb5f5b133852.png)

When using the utf seperators, suddenly the line doesn't fill the entire width anymore.
To achieve the above effect I merely did:
``` lisp
(setq utf-left-seperator (make-instance 'telephone-line-unicode-separator 
                                       :char #x2592))                     
(setq utf-right-seperator (make-instance 'telephone-line-unicode-separator
                                        :char #x2592                      
                                        :inverse-video nil))              
(setq                                                                     
 telephone-line-primary-left-separator 'utf-left-seperator                
 telephone-line-primary-right-separator 'utf-right-seperator)             
```

![image](https://user-images.githubusercontent.com/8513117/29921339-840b49c2-8e51-11e7-8866-9700b41da30e.png)

**Comment by dbordak** [comment]
Ok, think I fixed this

**Comment by bklaase** [comment]
yes, you did! :)
