### ISSUE TITLE
Weird custom face rendering

### ISSUE THREAD

**Issue by xahon** [dbordak/telephone-line#47]
Here is my init file chunk of config

I took code from [this example](https://github.com/dbordak/telephone-line/blob/master/examples.org#rainbow)

```Lisp
(use-package telephone-line
    :config
  (defface my-custom-face
      '((t (:background "white" :foreground "blue"))) "")

  (setq telephone-line-faces
        '((custom-color . (my-custom-face . my-custom-face ))
          (nil . (mode-line . mode-line-inactive))
          (accent . (telephone-line-accent-active . telephone-line-accent-inactive))))

  (setq telephone-line-lhs
        '((custom-color . (telephone-line-buffer-segment))
          (nil    . (telephone-line-vc-segment))
          (accent . (telephone-line-major-mode-segment))))
  (telephone-line-mode 1))
```

Here is actual bevahior  

![image](https://user-images.githubusercontent.com/18731681/31305985-8b342066-ab89-11e7-82a6-04dedb5cf9e0.png)

**Comment by dbordak** [comment]
That's odd... Not sure how that's inheriting the border... Or why the `height` doesn't seem to be working properly...

Does it look ok with the default config?

**Comment by xahon** [comment]
@dbordak yes, default config works fine. But it uses only 2 different colors (3 in evil). So i wanted to configure multiple colored segments

**Comment by dbordak** [comment]
Well, first thing I'd try doing is extending your custom face from an existing face (probably either mode-line or one of the telephone-line faces). To be honest, that example is pretty bad for a reference; I mostly only hosted it so I could re-generate the screenshots in the future.

So, something like
```
(defface my-custom-face
  '((t (:background "white" :foreground "blue" :inherit mode-line)))
```

**Comment by dbordak** [comment]
Actually, this might just be some bad interaction with `telephone-line-buffer-segment` and a non-nil supersegment. If it is, it's a bug and I'll fix it, but could you try using a different segment in your `custom-color` block?

Try the earlier thing, first, though.

**Comment by dbordak** [comment]
Oh, right! Third thing, could you check your messages/warnings buffers for anything relevant? Now that I look at it a bit more, I'm fairly certain this is because of a malformed XPM.
