### ISSUE TITLE
The sample command telephone-line-defsegment does not seem to work

### ISSUE THREAD

**Issue by ahungry** [dbordak/telephone-line#52]
Given that I attempt to define:

`(telephone-line-defsegment my-test "test")`

returns:

"Invalid lambda variable (face)"

**Comment by dbordak** [comment]
That error can't happen at the define, but where it's called. How are you inserting this segment?

**Comment by ahungry** [comment]
You're right, I forgot the surrounding face stuff and attempted to add it under one of the existing face blocks.  Thanks for an awesome package btw!
