### ISSUE TITLE
How to show and hide segments dynamically?

### ISSUE THREAD

**Issue by shackra** [dbordak/telephone-line#56]
I have the Python virtualenv environment shown on my mode-line with telephone-line, but when no environment is activated, I get a orange empty separator.

From your experience, what can you suggest to show and hide segments on telephone-line dynamically under certain conditions?

**Comment by dbordak** [comment]
Are you asking about hiding entire supersegments? Like, an entire color? If so, that's not possible and it'd be very difficult to implement -- There's too much pre-rendering done on a low level.

**Comment by shackra** [comment]
Well, yes. But I was having in mind a way to manipulate the variable that holds the segments as it seems more straightforward

**Comment by dbordak** [comment]
No, like I said, it's pre-rendered -- changing those variables won't do anything until you load a new buffer.

**Comment by dbordak** [comment]
I guess for this specific case, you could set this by major mode -- Enable the entire supersegment for python (whether you're in a venv or not) and disable it otherwise. Would that work?

**Comment by shackra** [comment]
Let me try that and I'll be back with you in a couple of days!

**Comment by shackra** [comment]
I went on a easier route: Will leave it always on.
