### ISSUE TITLE
Projectile in telephone-line

### ISSUE THREAD

**Issue by maindoor** [dbordak/telephone-line#61]
Is there a segment to display projectile project info on the mode line ?

**Comment by dbordak** [comment]
Not currently, no. What sort of thing are you imagining?

**Comment by anandpiyer** [comment]
@maindoor I use the following to show a "clickable" projectile project name  in the mode line:

```
(telephone-line-defsegment api--projectile-segment ()
    (if (and (fboundp 'projectile-project-name)
             (projectile-project-name))
        (propertize (format " [%s] " (concat (projectile-project-name)))
                    'face '(:inherit)
                    'display '(raise 0.0)
                    'help-echo "Switch Project"
                    'mouse-face '(:box 1)
                    'local-map (make-mode-line-mouse-map
                                'mouse-1 (lambda ()
                                           (interactive)
                                           (projectile-switch-project))))
      (propertize "×" 'face '(:inherit))))

```
Perhaps this is what you are looking for?

**Comment by hubgitname** [comment]
@anandpiyer 

Perfect. This is exactly what I am looking for. Hope @dbordak can include this in the default 
telephone line from Melpa.

**Comment by dbordak** [comment]
@anandpiyer you should submit PRs for your segments, I'd love to include more by default!

**Comment by anandpiyer** [comment]
@dbordak Submitted a PR for window number and projectile project name. I'll try to add more in the future.

**Comment by dbordak** [comment]
@anandpiyer the projectile segment is now included in the default config!

**Comment by dbordak** [comment]
@anandpiyer I'm changing the projectile segment a bit in the next commit -- I'm removing the brackets because I'd rather not include internal "separators" on any default segments (it looks kinda redundant since this is a package for adding fancy separators)

**Comment by anandpiyer** [comment]
Surer, sounds good! Thanks!
