### ISSUE TITLE
telephone-line-minor-mode-segment removed from defaults

### ISSUE THREAD

**Issue by bjorntropf** [dbordak/telephone-line#63]
Hi, in the last commit 220a1a4a89ca95be9ae1fab356b92296fff5b73a the telephone-line-minor-mode-segment was removed in line 310 of telephone-line.el.

It looks like this was removed by accident when adding other default segments.

Could you please add it back to the defaults? (So far this package was usable out-of-the-box.)

**Comment by dbordak** [comment]
That was intentional, actually. You can add it back in yourself if you want it, but the idea is to work on a whitelist rather than a blacklist -- most of the segments are intended to be better versions of minor mode lighters anyway.

**Comment by dbordak** [comment]
Just to expand on this, I didn't consider telephone-line to actually *be* usable out-of-the-box, `diminish` was practically required. There might be some lighters you're currently missing, but I do intend on adding more segments to compensate...

Alternatively, I could do a lightweight whitelist on the minor-mode-segment itself, in-package, since the list is already being parsed in there anyway. Would that be better?

**Comment by bjorntropf** [comment]
Thank you for your answer. I'll adjust my local configuration. 

Regarding the general use case for this issue: I'm using delight (similar to diminish) for all minor modes except flycheck. Seeing the FlyC:5/18 (see screenshot here: https://github.com/flycheck/flycheck) in the mode line tends to be very useful. Maybe a future segment could compensate for flycheck and similar packages like flymake?

**Comment by dbordak** [comment]
Oh, yeah, a flycheck segment is planned (and in fact I had been working on it, I think I just forgot, hehe)

**Comment by dbordak** [comment]
@bjorntropf I've just added a flycheck segment to the defaults in the latest commit. It's a bit lame, though, since it has unconfigurable faces as of yet.

**Comment by bjorntropf** [comment]
@dbordak Nice, great work!

> It's a bit lame, though, since it has unconfigurable faces as of yet.

This should be easily fixable for now by using the faces flycheck-warning and flycheck-error instead of orange/tomato. 

Having the status text like ":)" or "Problems: " in a global alist or similar would make customisation a bit easier. But you might already have that planned ;-)

**Comment by dbordak** [comment]
Already tried that, those faces default to an underline, which is terrible for a mode-line :/ (and I can't rightly overwrite users' faces). Also tried the `-list-` variants but those somehow failed to propertize at all?

**Comment by dbordak** [comment]
> One way to do it would be something like [...]
Now we're depending upon users *not* overwriting the face -- it's just not really worth doing it. I could just add a couple new faces, though.

> The proper way [...]

That's too much abstraction -- it'd be much easier to just have users define their own segment function. The alist is approaching the size of the function body anyway, and we're leaving out other customization people would want like hover style.
