### ISSUE TITLE
Some elements don't resize when frame is resized

### ISSUE THREAD

**Issue by mfiano** [dbordak/telephone-line#64]
When I resize the frame, some elements are not resizing with the text:

![Example](https://files.lispcoder.net/images/screenshots/img-20180405011042.png)

**Comment by dbordak** [comment]
You can try refreshing the separator caches --
```
(telephone-line-separator-clear-cache telephone-line-cubed-left)
(telephone-line-separator-clear-cache telephone-line-cubed-right)
```

**Comment by mfiano** [comment]
Thanks, almost. The middle one is messed up still.

![Example](https://files.lispcoder.net/images/screenshots/img-20180405014308.png)

**Comment by dbordak** [comment]
Sorry, missed that in the thumbnail
```
(telephone-line-separator-clear-cache telephone-line-cubed-hollow-left)
(telephone-line-separator-clear-cache telephone-line-cubed-hollow-right)
```

**Comment by mfiano** [comment]
Thanks, fixed.
