### ISSUE TITLE
Change color of evil's normal state indicator

### ISSUE THREAD

**Issue by mfiano** [dbordak/telephone-line#65]
How can I change the color of the modeline indicator for normal state? I think red is too jarring, and it's the state most often seen. I'd like to change it to something cooler, like a shade of blue. Everything else with the default configuration should remain the same.

**Comment by dbordak** [comment]
Visually, you can do it with `customize-face` -- the one you want is `telephone-line-evil-normal`. If you want to do it outside customize, I think you might need to create a theme file... but if all you want to do is configure this one variable, customize is probably the easiest.

**Comment by mfiano** [comment]
Thank you.
