### ISSUE TITLE
Theming glitches

### ISSUE THREAD

**Issue by ShashankaNataraj** [dbordak/telephone-line#70]
Hi Ive tried multiple dark themes:

Doom one:
![image](https://user-images.githubusercontent.com/650317/40769697-45b5d88e-64d6-11e8-9e07-122e3b80b1cf.png)

Doom Molokai:
![image](https://user-images.githubusercontent.com/650317/40769781-76011044-64d6-11e8-8ab8-8882f795e240.png)

Both of the themes above exhibit colors after the right arrow which look off from the rest of the coloring. Why dont the colors in my screenshots look like the screenshots in the readme?

**Comment by dbordak** [comment]
Are you on MacOS? If so, this is probably #54

**Comment by ShashankaNataraj** [comment]
Yep, Im on OSX. 

I remember the same problem used to occur with spacemacs' modeline as well.

Light themes are somewhat bearable though. Thanks for the blazingly fast reply!

I want to have only the evil state on one end and the git branch on the other end of the telephone line with nothing in between. How do I achieve that?! Ill probably open a new issue for that :)
