### ISSUE TITLE
Disable all colors in inactive modeline

### ISSUE THREAD

**Issue by ogdenwebb** [dbordak/telephone-line#83]
I know that the default Emacs mode-line has the same behaviour as the follow screenshot, but is there a way to achieve that? 

![2018-09-07-235356_936x1006_scrot](https://user-images.githubusercontent.com/9018005/45242914-805dd000-b2fa-11e8-96d2-c4b19442a45a.png)

**Comment by dbordak** [comment]
Just pushed up a potential fix for this. Lemme know if it works for you. As usual, wait for melpa to populate, etc.

**Comment by ogdenwebb** [comment]
> Just pushed up a potential fix for this.

Nice, it fixes that. Thank you!

>  wait for melpa to populate

I set my local/dev package directory, so I can just add :load-path in use-package declaration.
