### ISSUE TITLE
Telephone line logs error message

### ISSUE THREAD

**Issue by swarnendubiswas** [dbordak/telephone-line#9]
Not sure if this is serious, but I get to see this error message several times in my messages buffer.

Error during redisplay: (eval (telephone-line-add-subseparators (quote (misc-info-segment telephone-line-major-mode-segment)) (function telephone-line-abs-hollow-right) (quote nil))) signaled (void-
function misc-info-segment) [56 times]

**Comment by dbordak** [comment]
D'oh. I haven't been testing the default values.

This should go away once the next build hits MELPA.

**Comment by dbordak** [comment]
Alright, it should be resolved now.

**Comment by swarnendubiswas** [comment]
Error during redisplay: (eval (telephone-line-add-subseparators (quote (telephone-line-vc-segment telephone-line-erc-modified-channels-segment telephone-line-process-segment)) (function telephone-line-abs-hollow-left) (quote accent))) signaled (void-variable erc-modified-channels-object)
Error during redisplay: (eval (telephone-line-add-subseparators (quote (telephone-line-evil-tag-segment)) (function telephone-line-abs-hollow-left) (quote evil))) signaled (void-function telephone-line-evil

These are the messages that I get now, after the recent update.

**Comment by dbordak** [comment]
Ah, I see

     (telephone-line-vc-segment telephone-line-erc-modified-channels-segment telephone-line-process-segment)

You're using the example config from the readme? If you're not using evil, the default settings should be fine -- you don't need to customize the lhs/rhs or anything. If you want something a bit fancier, try this:

    (setq telephone-line-lhs
          '((nil    . (telephone-line-minor-mode-segment))
            (accent . (telephone-line-vc-segment
                       telephone-line-process-segment))
            (nil    . (telephone-line-buffer-segment))))
    (setq telephone-line-rhs
          '((nil    . (telephone-line-airline-position-segment))
            (accent . (telephone-line-major-mode-segment))
            (nil    . (telephone-line-misc-info-segment))))

**Comment by dbordak** [comment]
Just a heads up: In the latest version, I've changed the definitions to read Outward-In to being Left-to-Right. Nothing will break, but in order to keep the same theme, you'd need to change the rhs to 

    (setq telephone-line-rhs
          '((nil    . (telephone-line-misc-info-segment))
            (accent . (telephone-line-major-mode-segment))
            (nil    . (telephone-line-airline-position-segment))))
