### ISSUE TITLE
Telephone-line: use minions for minor-modes

### ISSUE THREAD

**Issue by sebasmonia** [dbordak/telephone-line#90]
I'll be honest I'm not entirely sure this is a bug or it just needs a different (new) segment, but telephone-line-minor-mode-segment shows the entire list even when minions-mode is active.

**Comment by dbordak** [comment]
yea, minions is implemented with a new variable, so it needs a new segment. Shouldn't be too hard, at least :P

**Comment by sebasmonia** [comment]
Looks like I need a new segment that displays the value of minions-mode-line-modes, as per the description in https://github.com/tarsius/minions/wiki.

I'm on mobile right now but will try that tomorrow. 
Thank you!

**Comment by sebasmonia** [comment]
Not a telephone-line issue. Couldn't get to create a segment yet but if I do, I will share it here/submit a PR.

**Comment by dbordak** [comment]
Nah, issues are for feature requests, too!

**Comment by dbordak** [comment]
Fixed by #92
