### ISSUE TITLE
Disable telephone line in term-mode (or any major mode)

### ISSUE THREAD

**Issue by ema2159** [dbordak/telephone-line#99]
Is there a way to do this? I don't like the way telephone line looks on my terminal (I use Shell Pop which pops up a terminal buffer down in the screen)

**Comment by ema2159** [comment]
Is there a way to do this? I don't like the way telephone line looks on my terminal (I use Shell Pop which pops up a terminal buffer down in the screen)

**Comment by AGitBoy** [comment]
Replace your call to `telephone-line-mode` with this
```
(if (display-graphic-p)
    (telephone-line-mode 2))
```

This will only enable `telephone-line-mode` automatically when not running in a terminal.

**Comment by ema2159** [comment]
That is not what I mean. I think its better to show you an image to be more clear
![telephone_line_screenshot](https://user-images.githubusercontent.com/17773218/53612141-cb182080-3b96-11e9-8ce0-7378cf8fed08.png)
                 ^
This is what I want to disable

**Comment by AGitBoy** [comment]
Oh, my bad. In that case, the following _should_ work according to the function documentation on it, but it isn't working on my machine, so I think it's a bug.
```elisp
;; Replace foo-mode with whatever hook you want
(add-hook 'foo-mode-hook
          lambda ()
          (interactive)
          (telephone-line-mode -1))
```

But it seems as though, even after disabling the mode, the prompt won't become disabled. I think it's a bug.

**Comment by ema2159** [comment]
Yes, I tried that and didn't work either so let's hope somebody fix this! Anyway, thank you for your help!

**Comment by dbordak** [comment]
I think this not working is related to the early-buffer issues. Have you tried setting `mode-line-format` to `nil` in the relevant buffers?

**Comment by ema2159** [comment]
> I think this not working is related to the early-buffer issues. Have you tried setting `mode-line-format` to `nil` in the relevant buffers?

This seems to work pretty fine

**Comment by dbordak** [comment]
> The `(telephone-line-mode)` function should be fixed though!

It's actually working as intended. To use it on a hook like that, it'd need to be a local mode -- In order for _anyone_ to enable it, they'd need to hook it onto *every* mode. Since it's global, you can't use a hook to _disable_ it either.

I could add another function to disable it in the current buffer, but there's no way I can make `(telephone-line-mode)` do that

**Comment by ema2159** [comment]
> I could add another function to disable it in the current buffer
^This sounds good, but shouldn't the `(telephone-line-mode)`  function be called `(telephone-line-global-mode)`  then?

**Comment by dbordak** [comment]
Possibly. That convention sorta exists, but AFAICT it's not used when the type of plugin is _assumed_ to be global -- for instance, the other powerline plugins, ivy, helm, etc.
